# Generated by Django 4.2.16 on 2024-09-10 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='service_info',
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='services',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.services'),
            preserve_default=False,
        ),
    ]
