# Generated by Django 4.2.16 on 2024-09-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about_alter_serviceinfo_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_uz',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='information_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='information_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='information_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_en',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_ru',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_uz',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='clientsfeedback',
            name='message_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clientsfeedback',
            name='message_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clientsfeedback',
            name='message_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clientsfeedback',
            name='profession_en',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='clientsfeedback',
            name='profession_ru',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='clientsfeedback',
            name='profession_uz',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faqtype',
            name='title_en',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='faqtype',
            name='title_ru',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='faqtype',
            name='title_uz',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='title_en',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='title_ru',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='title_uz',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='title_en',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='title_ru',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='title_uz',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='occupation_en',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='occupation_ru',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='occupation_uz',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_en',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_ru',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_uz',
            field=models.CharField(max_length=212, null=True),
        ),
    ]
