# Generated by Django 4.2.16 on 2024-09-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_about_description_en_about_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=212, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_en',
            field=models.CharField(max_length=212, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_ru',
            field=models.CharField(max_length=212, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_uz',
            field=models.CharField(max_length=212, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='information',
            field=models.TextField(verbose_name='information'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='information_en',
            field=models.TextField(null=True, verbose_name='information'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='information_ru',
            field=models.TextField(null=True, verbose_name='information'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='information_uz',
            field=models.TextField(null=True, verbose_name='information'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(max_length=212, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title_en',
            field=models.CharField(max_length=212, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title_ru',
            field=models.CharField(max_length=212, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title_uz',
            field=models.CharField(max_length=212, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='clientsfeedback',
            name='full_name',
            field=models.CharField(max_length=212, verbose_name='full_name'),
        ),
        migrations.AlterField(
            model_name='clientsfeedback',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='clientsfeedback',
            name='message_en',
            field=models.TextField(null=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='clientsfeedback',
            name='message_ru',
            field=models.TextField(null=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='clientsfeedback',
            name='message_uz',
            field=models.TextField(null=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='clientsfeedback',
            name='profession',
            field=models.CharField(max_length=212, verbose_name='profession'),
        ),
        migrations.AlterField(
            model_name='clientsfeedback',
            name='profession_en',
            field=models.CharField(max_length=212, null=True, verbose_name='profession'),
        ),
        migrations.AlterField(
            model_name='clientsfeedback',
            name='profession_ru',
            field=models.CharField(max_length=212, null=True, verbose_name='profession'),
        ),
        migrations.AlterField(
            model_name='clientsfeedback',
            name='profession_uz',
            field=models.CharField(max_length=212, null=True, verbose_name='profession'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_uz',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_en',
            field=models.TextField(null=True, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ru',
            field=models.TextField(null=True, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_uz',
            field=models.TextField(null=True, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='faqtype',
            name='title',
            field=models.CharField(max_length=212, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='faqtype',
            name='title_en',
            field=models.CharField(max_length=212, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='faqtype',
            name='title_ru',
            field=models.CharField(max_length=212, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='faqtype',
            name='title_uz',
            field=models.CharField(max_length=212, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=212, verbose_name='full_name'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=212, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=212, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title_en',
            field=models.CharField(max_length=212, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title_ru',
            field=models.CharField(max_length=212, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title_uz',
            field=models.CharField(max_length=212, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='full_name',
            field=models.CharField(max_length=212, verbose_name='full_name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='full_name',
            field=models.CharField(max_length=212, verbose_name='full_name'),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='title',
            field=models.CharField(max_length=212, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='title_en',
            field=models.CharField(max_length=212, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='title_ru',
            field=models.CharField(max_length=212, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='title_uz',
            field=models.CharField(max_length=212, null=True, verbose_name='title'),
        ),
    ]
