# Generated by Django 4.2.16 on 2024-09-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_about_description_alter_about_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='title')),
                ('title_uz', models.CharField(max_length=125, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=125, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=125, null=True, verbose_name='title')),
                ('tick', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='title')),
                ('title_uz', models.CharField(max_length=125, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=125, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=125, null=True, verbose_name='title')),
                ('price', models.IntegerField()),
                ('limit_date', models.CharField(max_length=125)),
                ('limit_user', models.CharField(max_length=125)),
                ('features', models.ManyToManyField(to='main.feature')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='tags',
            field=models.ManyToManyField(to='main.tag'),
        ),
    ]
