# Generated by Django 4.2.16 on 2024-10-02 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_about_description_alter_about_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=212, verbose_name='title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='services',
            name='service_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.servicetype'),
            preserve_default=False,
        ),
    ]
