# Generated by Django 4.2.16 on 2024-09-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_feature_tag_priceplan_projects_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='price',
            field=models.FloatField(),
        ),
    ]
