# Generated by Django 4.2.16 on 2024-10-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_servicetype_services_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='title_en',
            field=models.CharField(max_length=212, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='title_ru',
            field=models.CharField(max_length=212, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='title_uz',
            field=models.CharField(max_length=212, null=True, verbose_name='title'),
        ),
    ]
