# Generated by Django 4.2.16 on 2024-10-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_servicetype_title_en_servicetype_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='title_en',
            field=models.CharField(max_length=212, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='projects',
            name='title_ru',
            field=models.CharField(max_length=212, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='projects',
            name='title_uz',
            field=models.CharField(max_length=212, null=True, verbose_name='title'),
        ),
    ]
