# Generated by Django 4.2.16 on 2024-10-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tag_projects_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(max_length=212, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_uz',
            field=models.CharField(max_length=212, null=True),
        ),
    ]
